### ISSUE TITLE
Error While executing npm install

### ISSUE THREAD

**Issue by haroldb2** [nodegui/react-nodegui-starter#218]
Hello i was trying to install the npm but there was an error during the installation, attached are the log for the review of the problem

![image](https://user-images.githubusercontent.com/74793225/99980036-cb4a4d80-2d75-11eb-9730-c35aed5cd4f7.png)
![image](https://user-images.githubusercontent.com/74793225/99980133-e3ba6800-2d75-11eb-93ba-2a348e237b2d.png)

[2020-11-23T17_18_16_671Z-debug.log](https://github.com/nodegui/react-nodegui-starter/files/5583961/2020-11-23T17_18_16_671Z-debug.log)
[2020-11-23T17_18_52_310Z-debug.log](https://github.com/nodegui/react-nodegui-starter/files/5583962/2020-11-23T17_18_52_310Z-debug.log)
[2020-11-23T17_18_58_459Z-debug.log](https://github.com/nodegui/react-nodegui-starter/files/5583963/2020-11-23T17_18_58_459Z-debug.log)

**Comment by cocodrino** [comment]
I get a similar error in macOS, I previously installed CMake

```
➜  react-nodegui-starter git:(master) yarn
yarn install v1.21.1
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @nodegui/react-nodegui > @nodegui/nodegui > cmake-js > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @nodegui/react-nodegui > @nodegui/nodegui > cmake-js > request > har-validator@5.1.5: this library is no longer supported
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > chokidar > fsevents@2.1.3: Please update to v 2.2.x
warning webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @nodegui/packer@1.4.1" has unmet peer dependency "@nodegui/nodegui@>=0.15.0".
[4/4] 🔨  Building fresh packages...
[4/4] ⠠ @nodegui/nodegui
[-/4] ⠠ waiting...
[3/4] ⠠ fsevents
error /Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/@nodegui/nodegui: Command failed.
Exit code: 1
Command: cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)
Arguments: 
Directory: /Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/@nodegui/nodegui
Output:
> @nodegui/nodegui@0.25.0 setupqt /Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/@nodegui/nodegui
> cross-env node ./scripts/setupMiniQt.js

Minimal Qt 5.14.1 setup:
Archive already exists at /Users/Admin/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z. Skipping download....
Extracting /Users/Admin/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z to /Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
Archive already exists at /Users/Admin/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z. Skipping download....
Extracting /Users/Admin/Library/Caches/nodegui-mini-qt-nodejs/5.14.1-0-202001241000qttools-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z to /Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/@nodegui/nodegui/miniqt ...
Error: Exited with code 2
    at ChildProcess.<anonymous> (/Users/Admin/Downloads/proj/avanti/nodegui/react-nodegui-starter/node_modules/7zip-min/index.js:64:19)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.25.0 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.25.0 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by a7ul** [comment]
@cocodrino  for your case, it seems like the zip file downloaded for qt was corrupt so 7zip failed to extract it. 

Can you do 

`rm -rf /Users/Admin/Library/Caches/nodegui*`
and `rm -rf node_modules`

then do `npm install`

**Comment by a7ul** [comment]
@haroldb2 the error mentions that cmake cant find your visual studio 2019 instance.

**Comment by blessdarah** [comment]
I also have this same error on windows. I am stuck and don't know what to do.
I would have loved to test and work on it.
