### ISSUE TITLE
Windows: Cant run npm install. VCBuild error

### ISSUE THREAD

**Issue by erikswed** [nodegui/react-nodegui-starter#4]
I follow the instructions like:

Clone this repository:
git clone https://github.com/nodegui/react-nodegui-starter
Go into the repository:
cd react-nodegui-starter 
Install dependencies:
npm install
 Run the app:
npm start

and I got this strange error..:
When I do npm install it want me to install Microsoft Visual Studio 2005 SDK

Please advice?

This is cmd output: (sorry I have Swedish language Computer)

```
C:\Users>cd C:\Users\user\source\repos\react-nodegui-starter

C:\Users\user\source\repos\react-nodegui-starter>npm install

> @nodegui/nodegui@0.1.3 install C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui
> npm -v

6.4.1

> @nodegui/qode@1.0.2 postinstall C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\qode
> node install.js

Local Qode 1.0.2 archive doesnt exists... Copying Qode from cache...
Extracting binaries...

> @nodegui/nodegui@0.1.3 postinstall C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui
> npm run build:addon


> @nodegui/nodegui@0.1.3 build:addon C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui
> node-gyp -j 8 configure build


C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" -j 8 configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" -j 8 configure build )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
MSBUILD : error MSB3428: Det gick inte att läsa in Visual C++-komponenten VCBuild.exe. Du åtgärdar detta genom att installera .NET Framework 2.0
 SDK, installera Microsoft Visual Studio 2005 eller genom att lägga till sökvägen till komponenten i systemsökvägen om den är installerad på en
annan plats.  [C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "-j" "8" "configure" "build"
gyp ERR! cwd C:\Users\user\source\repos\react-nodegui-starter\node_modules\@nodegui\nodegui
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.1.3 build:addon: `node-gyp -j 8 configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.1.3 build:addon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-08-18T19_17_41_045Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.1.3 postinstall: `npm run build:addon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-08-18T19_17_41_573Z-debug.log

C:\Users\user\source\repos\react-nodegui-starter>
```
![image](https://user-images.githubusercontent.com/3285249/63229283-269aa100-c1ff-11e9-9114-b1225b95b64e.png)

**Comment by a7ul** [comment]
Hi @erikswed  Have you installed Visual studio 2017 as per the docs?

**Comment by a7ul** [comment]
In windows you need to have visual studio 2017 (not 2019) installed.

**Comment by erikswed** [comment]
I only have Visual Studio 2019

**Comment by a7ul** [comment]
node-gyp (NodeJs's build system) is not compatible with Visual Studio 2019 yet sadly. So you will need to install Visual Studio 2017 unfortunately to work with native modules in NodeJs. @erikswed

**Comment by erikswed** [comment]
Thanks I installed Visual studio 2017, what tools should I install ? I selected Node.js developmen but that is not enough I still get the error. Please advice

![image](https://user-images.githubusercontent.com/3285249/63252883-f8ee4000-c270-11e9-90c9-43108584b2fb.png)

**Comment by a7ul** [comment]
Install Visual Studio Community 2017. Download the Visual studio Installer and install Visual Studio Community 2017. Make sure to choose "Desktop development with C++ " workload and install it. PS: Visual Studio 2019 will not work since NodeJS build toolchain doesnt support it aswell.

**Comment by a7ul** [comment]
Did it work @erikswed ?

**Comment by erikswed** [comment]
Yes it did Thanks Master

**Comment by cjones1313** [comment]
I'm running into the same issue but I have VS2017 installed. I also verified that the correct components are installed. Any ideas? 

Not sure if this makes a difference but I also have VS2010 and VS2015 installed. 

![image](https://user-images.githubusercontent.com/54443993/63597431-7248a400-c58b-11e9-85ca-ea2ae484fb5f.png)

**Comment by iflp** [comment]
[Direct link to download the 2017 community edition installer](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15) :)
