### ISSUE TITLE
npm ERR! Failed at the react-nodegui-starter@1.0.0 start script.

### ISSUE THREAD

**Issue by yusuf987** [nodegui/react-nodegui-starter#77]
```
yusuf-MacBook-Air-2:react-nodegui-starter-master yusuf$ npm start

> react-nodegui-starter@1.0.0 start /Users/yusuf/Documents/Node_GUI/downloaded/react-nodegui-starter-master
> qode --inspect ./dist/index.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/yusuf/Documents/Node_GUI/downloaded/react-nodegui-starter-master/node_modules/@nodegui/qode/dist/1.0.6/qode EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-nodegui-starter@1.0.0 start: `qode --inspect ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-nodegui-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yusuf/.npm/_logs/2020-02-02T07_15_21_719Z-debug.log
```

at the end when I am running npm start receiving above error 
can someone help me to solve this?

thanks

**Comment by Solant** [comment]
you should first run `npm run dev` and then `npm run start`, as you need some bundles from webpack build
